CREATE TABLE Users (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    username NVARCHAR(100) UNIQUE NOT NULL,
    password_hash NVARCHAR(255) NOT NULL,
    [role] NVARCHAR(50) NOT NULL DEFAULT 'Patient',
    created_at DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET()
);
GO

CREATE TABLE Patients (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    user_id UNIQUEIDENTIFIER REFERENCES Users(id) ON DELETE SET NULL,
    first_name NVARCHAR(100) NOT NULL,
    last_name NVARCHAR(100) NOT NULL,
    date_of_birth DATE NOT NULL,
    phone_number NVARCHAR(20) UNIQUE,
    is_deleted BIT NOT NULL DEFAULT 0,
    created_at DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
    updated_at DATETIMEOFFSET,
    updated_by_user_id UNIQUEIDENTIFIER REFERENCES Users(id)
);
GO

CREATE TABLE Staff (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    user_id UNIQUEIDENTIFIER REFERENCES Users(id) ON DELETE SET NULL,
    first_name NVARCHAR(100) NOT NULL,
    last_name NVARCHAR(100) NOT NULL,
    [position] NVARCHAR(100) NOT NULL,
    hire_date DATE NOT NULL,
    is_deleted BIT NOT NULL DEFAULT 0
);
GO

CREATE TABLE Departments (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [name] NVARCHAR(150) UNIQUE NOT NULL,
    [description] NVARCHAR(MAX)
);
GO

CREATE TABLE Doctors (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    staff_id UNIQUEIDENTIFIER UNIQUE REFERENCES Staff(id) ON DELETE CASCADE,
    department_id UNIQUEIDENTIFIER REFERENCES Departments(id) ON DELETE SET NULL,
    specialization NVARCHAR(150) NOT NULL
);
GO

CREATE TABLE Appointments (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    patient_id UNIQUEIDENTIFIER NOT NULL REFERENCES Patients(id),
    doctor_id UNIQUEIDENTIFIER NOT NULL REFERENCES Doctors(id),
    appointment_date DATETIME2 NOT NULL,
    [status] NVARCHAR(50) NOT NULL DEFAULT 'Scheduled',
    is_deleted BIT NOT NULL DEFAULT 0,
    created_at DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
    updated_at DATETIMEOFFSET,
    updated_by_user_id UNIQUEIDENTIFIER REFERENCES Users(id)
);
GO

CREATE TABLE MedicalRecords (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    patient_id UNIQUEIDENTIFIER NOT NULL REFERENCES Patients(id),
    appointment_id UNIQUEIDENTIFIER REFERENCES Appointments(id),
    notes NVARCHAR(MAX),
    created_at DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
    updated_at DATETIMEOFFSET,
    updated_by_user_id UNIQUEIDENTIFIER REFERENCES Users(id)
);
GO

CREATE TABLE Diagnoses (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    code NVARCHAR(20) UNIQUE NOT NULL,
    [name] NVARCHAR(255) NOT NULL,
    [description] NVARCHAR(MAX)
);
GO

CREATE TABLE RecordDiagnoses (
    record_id UNIQUEIDENTIFIER NOT NULL REFERENCES MedicalRecords(id) ON DELETE CASCADE,
    diagnosis_id UNIQUEIDENTIFIER NOT NULL REFERENCES Diagnoses(id) ON DELETE NO ACTION,
    PRIMARY KEY (record_id, diagnosis_id)
);
GO

CREATE TABLE Medications (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [name] NVARCHAR(150) NOT NULL,
    manufacturer NVARCHAR(150),
    [description] NVARCHAR(MAX)
);
GO

CREATE TABLE Prescriptions (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    medical_record_id UNIQUEIDENTIFIER NOT NULL REFERENCES MedicalRecords(id),
    doctor_id UNIQUEIDENTIFIER NOT NULL REFERENCES Doctors(id),
    issue_date DATE NOT NULL DEFAULT GETDATE(),
    expiry_date DATE,
    created_at DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
    updated_at DATETIMEOFFSET,
    updated_by_user_id UNIQUEIDENTIFIER REFERENCES Users(id)
);
GO

CREATE TABLE PrescriptionItems (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    prescription_id UNIQUEIDENTIFIER NOT NULL REFERENCES Prescriptions(id) ON DELETE CASCADE,
    medication_id UNIQUEIDENTIFIER NOT NULL REFERENCES Medications(id) ON DELETE NO ACTION,
    dosage NVARCHAR(100) NOT NULL,
    frequency NVARCHAR(100) NOT NULL,
    quantity INT NOT NULL
);
GO

CREATE TABLE Rooms (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    department_id UNIQUEIDENTIFIER REFERENCES Departments(id) ON DELETE SET NULL,
    room_number NVARCHAR(10) NOT NULL,
    [type] NVARCHAR(50) NOT NULL,
    capacity INT NOT NULL DEFAULT 1
);
GO

CREATE TABLE Admissions (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    patient_id UNIQUEIDENTIFIER NOT NULL REFERENCES Patients(id),
    room_id UNIQUEIDENTIFIER NOT NULL REFERENCES Rooms(id),
    admission_date DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    discharge_date DATETIME2,
    reason NVARCHAR(MAX)
);
GO

CREATE TABLE Bills (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    patient_id UNIQUEIDENTIFIER NOT NULL REFERENCES Patients(id),
    admission_id UNIQUEIDENTIFIER REFERENCES Admissions(id),
    issue_date DATE NOT NULL DEFAULT GETDATE(),
    due_date DATE,
    total_amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    [status] NVARCHAR(50) NOT NULL DEFAULT 'Unpaid'
);
GO

CREATE NONCLUSTERED INDEX idx_patients_last_name
ON Patients(last_name);
GO

CREATE NONCLUSTERED INDEX idx_active_appointments_on_doctor_date
ON Appointments(doctor_id, appointment_date)
WHERE is_deleted = 0;